
services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true


    CustomerManagementFrameworkBundle\Newsletter\Queue\NewsletterQueueInterface:
        class: CustomerManagementFrameworkBundle\Newsletter\Queue\DefaultNewsletterQueue

    CustomerManagementFrameworkBundle\Newsletter\Manager\NewsletterManagerInterface:
        class: CustomerManagementFrameworkBundle\Newsletter\Manager\DefaultNewsletterManager

    CustomerManagementFrameworkBundle\Newsletter\ProviderHandler\Mailchimp\MailChimpExportService:
        arguments:
            - '@DrewM\MailChimp\MailChimp'

    CustomerManagementFrameworkBundle\Newsletter\ProviderHandler\Newsletter2Go\Newsletter2GoExportService:
        arguments:
            - '@NL2GO\Newsletter2Go_REST_Api'

    CustomerManagementFrameworkBundle\Newsletter\ProviderHandler\Mailchimp\SegmentExporter: ~

    CustomerManagementFrameworkBundle\Newsletter\ProviderHandler\Mailchimp\TemplateExporter: ~

    CustomerManagementFrameworkBundle\Newsletter\ProviderHandler\Newsletter2Go\TemplateExporter:
        arguments:
            - '@NL2GO\Newsletter2Go_REST_Api'
            - 'template-id'

    CustomerManagementFrameworkBundle\Newsletter\ProviderHandler\Mailchimp\CustomerExporter\SingleExporter: ~
    CustomerManagementFrameworkBundle\Newsletter\ProviderHandler\Mailchimp\CustomerExporter\BatchExporter: ~

    CustomerManagementFrameworkBundle\Newsletter\ProviderHandler\Mailchimp\WebhookProcessor: ~
    CustomerManagementFrameworkBundle\Newsletter\ProviderHandler\Mailchimp\UpdateFromMailchimpProcessor: ~
    CustomerManagementFrameworkBundle\Newsletter\ProviderHandler\Mailchimp\CliSyncProcessor:
        arguments:
           - '%pimcore_customer_management_framework.newsletter.mailchimp.cliUpdatesPimcoreUserName%'

    CustomerManagementFrameworkBundle\Newsletter\ProviderHandler\Newsletter2Go\CliSyncProcessor:
        class: CustomerManagementFrameworkBundle\Newsletter\ProviderHandler\Newsletter2Go\CliSyncProcessor

    DrewM\MailChimp\MailChimp:
        arguments:
            - '%pimcore_customer_management_framework.newsletter.mailchimp.apiKey%'


    NL2GO\Newsletter2Go_REST_Api:
        arguments:
            - '%pimcore_customer_management_framework.newsletter.newsletter2Go.apiKey%'
            - '%pimcore_customer_management_framework.newsletter.newsletter2Go.username%'
            - '%pimcore_customer_management_framework.newsletter.newsletter2Go.password%'


    cmf.document.newsletter.factory.segmentAddressSource:
        class: Pimcore\Document\Newsletter\DefaultAddressSourceAdapterFactory
        arguments:
            - 'CustomerManagementFrameworkBundle\Newsletter\AddressSource\SegmentAddressSource'


    CustomerManagementFrameworkBundle\Event\NewsletterTerminateListener:
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onTerminate }
            - { name: kernel.event_listener, event: console.terminate, method: onTerminate }